const mongoose = require("mongoose");

const AnnualLeaveSchema = new mongoose.Schema({
  employeeId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  leaveType: { type: String, default: ["Annual Leave", "Maternity Leave"], required: true },
  status: { 
    type: String, 
    enum: ["Pending", "RecommendedBySectional", "RecommendedByDepartmental", "Approved", "Rejected"], 
    default: "Pending"
  },
  createdAt: { type: Date, default: Date.now },
  submissionDate: { type: Date, default: Date.now },
  employeeName: { type: String, required: true },
  personNumber: { type: String, required: true },
  department: { type: String, required: true },
  sector: { type: String },
  daysApplied: { type: Number, required: true },
  startDate: { type: Date, required: true },
  endDate: { type: Date, required: true },
  addressWhileAway: { type: String },
  emailAddress: { type: String },
  phoneNumber: { type: String },
  reason: { type: String, required: true },
  leaveBalanceBF: { type: Number, default: 0 },
  currentYearLeave: { type: Number, default: 0 },
  totalLeaveDays: { type: Number },
  leaveTakenThisYear: { type: Number, default: 0 },
  leaveBalanceDue: { type: Number },
  leaveApplied: { type: Number, required: true },
  leaveBalanceCF: { type: Number },
  computedBy: { type: String },
  computedDate: { type: Date },
  sectionalHeadName: String,
  departmentalHeadName: String,
  HRDirectorName: String,
  approvals: [
    {
      approverRole: String,
      status: { type: String, default: "Pending" },
      comment: String,
      updatedAt: Date,
    },
  ],
  sectionalHeadRecommendation: { type: String, default: "Pending" },
  sectionalHeadDate: String,
  departmentalHeadRecommendation: { type: String, default: "Pending" },
  departmentalHeadDate: String,
  departmentalHeadDaysGranted: Number,
  departmentalHeadStartDate: Date,
  departmentalHeadLastDate: Date,
  departmentalHeadResumeDate: Date,
  approverRecommendation: { type: String, default: "Pending" },
  approverDate: String,
  status: { type: String, default: "Pending" },
  createdAt: { type: Date, default: Date.now },
});
module.exports = mongoose.model("AnnualLeave", AnnualLeaveSchema);